### ISSUE TITLE
Crash on install -- need to bump pandas or numpy version ?

### ISSUE THREAD

**Issue by urbanophile** [ADGEfficiency/nem-data#34]
Installing nem-data in new  virtual environment with conda on linux (Ubuntu 22.04 via WSL) generates an error. I think this is caused because of breaking in changes in either numpy 2.0 or pandas 2.0 ( see https://stackoverflow.com/questions/78634235/numpy-dtype-size-changed-may-indicate-binary-incompatibility-expected-96-from). Probably solved by bumping pandas/numpy to at least 2.0. 

```
> ~/ conda create -n eda python=3.10                    
Retrieving notices: ...working... done
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/matt/miniconda3/envs/eda

  added / updated specs:
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.8                |       h5eee18b_6         262 KB
    pip-24.2                   |  py310h06a4308_0         2.3 MB
    python-3.10.14             |       h955ad1f_1        26.8 MB
    setuptools-72.1.0          |  py310h06a4308_0         2.4 MB
    wheel-0.43.0               |  py310h06a4308_0         110 KB
    ------------------------------------------------------------
                                           Total:        31.9 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main 
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu 
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h5eee18b_6 
  ca-certificates    pkgs/main/linux-64::ca-certificates-2024.7.2-h06a4308_0 
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.38-h1181459_1 
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_1 
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-11.2.0-h1234567_1 
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1 
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-11.2.0-h1234567_1 
  libuuid            pkgs/main/linux-64::libuuid-1.41.5-h5eee18b_0 
  ncurses            pkgs/main/linux-64::ncurses-6.4-h6a678d5_0 
  openssl            pkgs/main/linux-64::openssl-3.0.14-h5eee18b_0 
  pip                pkgs/main/linux-64::pip-24.2-py310h06a4308_0 
  python             pkgs/main/linux-64::python-3.10.14-h955ad1f_1 
  readline           pkgs/main/linux-64::readline-8.2-h5eee18b_0 
  setuptools         pkgs/main/linux-64::setuptools-72.1.0-py310h06a4308_0 
  sqlite             pkgs/main/linux-64::sqlite-3.45.3-h5eee18b_0 
  tk                 pkgs/main/linux-64::tk-8.6.14-h39e8969_0 
  tzdata             pkgs/main/noarch::tzdata-2024a-h04d1e81_0 
  wheel              pkgs/main/linux-64::wheel-0.43.0-py310h06a4308_0 
  xz                 pkgs/main/linux-64::xz-5.4.6-h5eee18b_1 
  zlib               pkgs/main/linux-64::zlib-1.2.13-h5eee18b_1 


Proceed ([y]/n)? y


Downloading and Extracting Packages:
                                                                                                                                  
Preparing transaction: done                                                                                                       
Verifying transaction: done                                                                                                       
Executing transaction: done                                                                                                       
#                                                                                                                                 
# To activate this environment, use
#
#     $ conda activate eda
#
# To deactivate an active environment, use
#
#     $ conda deactivate

❯ conda activate eda                             
❯ pip install nemdata                                     
Collecting nemdata
  Downloading nemdata-0.3.6-py3-none-any.whl.metadata (3.9 kB)
Collecting click<9.0.0,>=8.1.3 (from nemdata)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting lxml<5.0.0,>=4.9.1 (from nemdata)
  Downloading lxml-4.9.4-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting pandas<2.0.0,>=1.5.2 (from nemdata)
  Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting pyarrow<11.0.0,>=10.0.1 (from nemdata)
  Downloading pyarrow-10.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Collecting pydantic<2.0.0,>=1.10.2 (from nemdata)
  Downloading pydantic-1.10.18-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (152 kB)
Collecting requests<3.0.0,>=2.28.1 (from nemdata)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting rich<13.0.0,>=12.6.0 (from nemdata)
  Downloading rich-12.6.0-py3-none-any.whl.metadata (18 kB)
Collecting python-dateutil>=2.8.1 (from pandas<2.0.0,>=1.5.2->nemdata)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas<2.0.0,>=1.5.2->nemdata)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting numpy>=1.21.0 (from pandas<2.0.0,>=1.5.2->nemdata)
  Downloading numpy-2.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting typing-extensions>=4.2.0 (from pydantic<2.0.0,>=1.10.2->nemdata)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting charset-normalizer<4,>=2 (from requests<3.0.0,>=2.28.1->nemdata)
  Downloading charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.28.1->nemdata)
  Using cached idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3.0.0,>=2.28.1->nemdata)
  Downloading urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.28.1->nemdata)
  Using cached certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
Collecting commonmark<0.10.0,>=0.9.0 (from rich<13.0.0,>=12.6.0->nemdata)
  Using cached commonmark-0.9.1-py2.py3-none-any.whl.metadata (5.7 kB)
Collecting pygments<3.0.0,>=2.6.0 (from rich<13.0.0,>=12.6.0->nemdata)
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.1->pandas<2.0.0,>=1.5.2->nemdata)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Downloading nemdata-0.3.6-py3-none-any.whl (10 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Downloading lxml-4.9.4-cp310-cp310-manylinux_2_28_x86_64.whl (7.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 8.2 MB/s eta 0:00:00
Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 6.8 MB/s eta 0:00:00
Downloading pyarrow-10.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (35.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.9/35.9 MB 6.1 MB/s eta 0:00:00
Downloading pydantic-1.10.18-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 8.9 MB/s eta 0:00:00
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Downloading rich-12.6.0-py3-none-any.whl (237 kB)
Using cached certifi-2024.7.4-py3-none-any.whl (162 kB)
Downloading charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Using cached idna-3.7-py3-none-any.whl (66 kB)
Downloading numpy-2.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 6.0 MB/s eta 0:00:00
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading urllib3-2.2.2-py3-none-any.whl (121 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: pytz, commonmark, urllib3, typing-extensions, six, pygments, numpy, lxml, idna, click, charset-normalizer, certifi, rich, requests, python-dateutil, pydantic, pyarrow, pandas, nemdata
Successfully installed certifi-2024.7.4 charset-normalizer-3.3.2 click-8.1.7 commonmark-0.9.1 idna-3.7 lxml-4.9.4 nemdata-0.3.6 numpy-2.1.0 pandas-1.5.3 pyarrow-10.0.1 pydantic-1.10.18 pygments-2.18.0 python-dateutil-2.9.0.post0 pytz-2024.1 requests-2.32.3 rich-12.6.0 six-1.16.0 typing-extensions-4.12.2 urllib3-2.2.2
❯ nemdata
Traceback (most recent call last):
  File "/home/matt/miniconda3/envs/eda/bin/nemdata", line 5, in <module>
    from nemdata.cli import cli
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/nemdata/__init__.py", line 4, in <module>
    from nemdata.downloader import download
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/nemdata/downloader.py", line 4, in <module>
    import pandas as pd
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
❯ nemdata --help                                        
Traceback (most recent call last):
  File "/home/matt/miniconda3/envs/eda/bin/nemdata", line 5, in <module>
    from nemdata.cli import cli
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/nemdata/__init__.py", line 4, in <module>
    from nemdata.downloader import download
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/nemdata/downloader.py", line 4, in <module>
    import pandas as pd
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/pandas/compat/__init__.py", line 18, in <module>
    from pandas.compat.numpy import (
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/home/matt/miniconda3/envs/eda/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by ADGEfficiency** [comment]
@urbanophile - thanks for posting this - it's fixed in https://github.com/ADGEfficiency/nem-data/pull/35 and in `nemdata==0.3.7`
